repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # use the latest stable version
    hooks:
      - id: detect-secrets
        name: detect-secrets
        entry: detect-secrets-hook
        language: python
        args: ['--baseline', '.secrets.baseline']
