name: Asn1 Unit Tests

on:
  pull_request:
    paths:
      - projects/asn1_unittest/**
      - src/common/**
      - src/asn1/**

permissions:
  contents: read

jobs:
  UnitTest:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: trustcore-test

      - name: Checkout conditional tests
        uses: actions/checkout@v4
        with:
          repository: digicert/device-trust-jenkins-conditional-tests
          ref: main
          path: jct
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full cproto cmake
          python3 -m pip install --upgrade jenkinsapi
          sudo apt-get install -y lcov
          lcov --version
          
      - name: Build and Run Unit Tests
        run: |
          cd trustcore-test/projects/asn1_unittest
          CM_ENV_CODE_COVERAGE=1 ./build.sh
          ./run.sh
          cd ../../../

      - name: Baseline Coverage
        run: |
          lcov --no-external --capture --initial --directory . --output-file /tmp/asn1_base.info

      - name: Capture Coverage
        run: |
          lcov --no-external --capture --directory . --output-file /tmp/asn1_test.info
          lcov --add-tracefile /tmp/asn1_base.info --add-tracefile /tmp/asn1_test.info --output-file /tmp/asn1_total.info

      - name: Print Coverage Summary
        run: |
          echo "Coverage Summary:"
          lcov --list /tmp/asn1_total.info
