name: Common Unit Tests

on:
  pull_request:
    paths:
      - projects/common_unittest/**
      - src/common/**

permissions:
  contents: read

jobs:
  UnitTest:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: trustcore-test

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full cproto cmake
          python3 -m pip install --upgrade jenkinsapi
          sudo apt-get install -y lcov
          lcov --version
          
      - name: Build and Run Unit Tests
        run: |
          cd trustcore-test/projects/common_unittest
          CM_ENV_CODE_COVERAGE=1 ./build.sh
          ./run.sh
          cd ../../../

      - name: Baseline Coverage
        run: |
          lcov --no-external --capture --initial --directory . --output-file /tmp/common_base.info

      - name: Capture Coverage
        run: |
          lcov --no-external --capture --directory . --output-file /tmp/common_test.info
          lcov --add-tracefile /tmp/common_base.info --add-tracefile /tmp/common_test.info --output-file /tmp/common_total.info

      - name: Print Coverage Summary
        run: |
          echo "Coverage Summary:"
          lcov --list /tmp/common_total.info
