name: Crypto Interop Test

on:
  pull_request:
    paths:
      - projects/crypto_interop_test/**
      - src/common/**
      - src/crypto/**
      - src/crypto_interface/**
      - src/cap/**
      - src/fips/**

permissions:
  contents: read

jobs:
  UnitTest:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: trustcore-test

      - name: Checkout conditional tests
        uses: actions/checkout@v4
        with:
          repository: digicert/device-trust-jenkins-conditional-tests
          ref: main
          path: jct
          token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full cproto cmake
          python3 -m pip install --upgrade jenkinsapi
          sudo apt-get install autoconf automake autotools-dev libsigsegv2 m4 libtool libltdl-dev libltdl7
          sudo apt-get install ninja-build
          
      - name: Build and Run Unit Tests
        run: |
          cd trustcore-test/projects/crypto_interop_test
          ./build.sh
          ./run.sh
          cd ../../../
