name: Crypto Interface Unit Tests

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - projects/cryptointerface_unittest/**
      - src/common/**
      - src/crypto/**
      - src/crypto_interface/**
      - src/cap/**
      - src/fips/**

permissions:
  contents: read

jobs:
  UnitTest:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: trustcore-test

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install ruby-full cproto cmake
          python3 -m pip install --upgrade jenkinsapi
          sudo apt-get install -y lcov
          lcov --version
          
      - name: Build and Run Unit Tests
        run: |
          cd trustcore-test/projects/cryptointerface_unittest
          CM_ENV_CODE_COVERAGE=1 ./build.sh --quick
          ./run.sh
          cd ../../../

      - name: Baseline Coverage
        run: |
          lcov --no-external --capture --initial --directory . --output-file /tmp/ci_base.info

      - name: Capture Coverage
        run: |
          lcov --no-external --capture --directory . --output-file /tmp/ci_test.info
          lcov --add-tracefile /tmp/ci_base.info --add-tracefile /tmp/ci_test.info --output-file /tmp/ci_total.info

      - name: Print Coverage Summary
        run: |
          echo "Coverage Summary:"
          lcov --list /tmp/ci_total.info
