name: Detect Secrets

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  detect-secrets:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Detect Secrets
        run: pip install detect-secrets

      - name: Run detect-secrets
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Fetch the base branch
            git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
            # Get all changed files in the PR
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }})
          else
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          fi
          
          if [ -n "$CHANGED_FILES" ]; then
            for FILE in $CHANGED_FILES; do
              echo "Scanning $FILE for secrets..."
              detect-secrets-hook --baseline .secrets.baseline "$FILE"
            done
          else
            echo "No files changed"
          fi
